name: Trigger when issue is created

  on:
    issues:
      types: [opened]
  jobs:
    Trigger thw workflow:
    runs-on: ubuntu-latest
    steps:
    - name: dump the context
      run: echo '${{ tojson(github.event) }}' | jq
      shell: bash
