name: Trigger when issue is created

on:
  issues:
    types: [opened]
jobs:
  comment-the-workflow:
   runs-on: ubuntu-latest
   steps:
   - name: dump the context
     run: echo '${{ toJson(github.event) }}' | jq
     shell: bash
  
  comment-the-issue-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comments with API
        run: |
          gh api -X POST \
          https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -fbody='
          Issue comment from api call
          '
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
  
